site_name: Content Generator
theme:
  name: material
  palette:
    - scheme: default
      primary: red
      accent: deep-purple
  font:
    text: Roboto
    code: Roboto Mono
nav:
  - Home: index.md
  - Guide:
      - App Overview: app_overview.md
      - Docker Setup: docker.md
      - REST API Deployment: rest_api.md
  - Feedback: feedback.md
  - Code Reference:
      - Main Module: main.md
